Web.CustomerSite/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.CustomerSite.Services;

namespace Web.CustomerSite.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderApiClient _orderApiClient;
        private readonly IConfiguration _configuration;

        public OrderController(IOrderApiClient orderApiClient, IConfiguration configuration)
        {
            _orderApiClient = orderApiClient;
            _configuration = configuration;
        }

        [Authorize]
        public async Task<IActionResult> IndexAsync()
        {
            var results = await _orderApiClient.GetMyOrder();
            foreach(var item in results)
            {
                item.ImgUrl = _configuration["Domain:Default"] + item.ImgUrl;
            }
            return View(results);
        }

        [Authorize]
        public async Task<IActionResult> Remove(int productId, int orderId)
        {
            var results = await _orderApiClient.DeleteOrderItem(productId, orderId);
            return RedirectToAction("Index", "Order");
        }
    }
}

Web.CustomerSite/Controllers/RatingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Threading.Tasks;
using Web.CustomerSite.Services;

namespace Web.CustomerSite.Controllers
{
    public class RatingsController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;

        public RatingsController(IProductApiClient productApiClient, IConfiguration configuration)
        {
            _productApiClient = productApiClient;
            _configuration = configuration;
        }

        [Authorize]
        [Route("/Ratings/{name}-{productId}-{orderId}")]
        public async Task<IActionResult> Index(int productId, int orderId)
        {
            var result = await _productApiClient.GetProductForRating(productId);
            List<string> temp = new List<string>();
            foreach (string item in result.ProductFileImages)
            {
                temp.Add(_configuration["Domain:Default"] + item);
            }
            result.ProductFileImages = temp;
            return View(result);
        }

        public async Task<IActionResult> SetRating(int Id, int rank)
        {
            await _productApiClient.PostRating(Id, rank);
            return RedirectToAction("Index", "Order");
        }
    }
}

Web.CustomerSite/Views/Order/Index.cshtml
@model IList<Web.ShareModels.ViewModels.OrderVm>

@{
    ViewData["Title"] = "My Order Page";
}

@if (Model.Count != 0)
{
    <form method="post">
        <br /><br />
        <h2 class="text-info">Đơn hàng của bạn!</h2>
        <div class="form-text">
            Bạn chỉ có thể hủy các đơn hàng chưa được xác nhận hoặc các đơn hàng chưa được giao!
        </div>
        <br />
        <div class="container border border-secondary rounded " style="padding: 15px; border-radius:5px; border:1px solid #bbb9b9">
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-striped rounded" style="width:100%; border-radius:5px; border:1px solid #bbb9b9 ">
                        <tr class="table-info">
                            <th style="text-align:center; width:20%">
                                <label>Hình ảnh</label>
                            </th>
                            <th style="text-align:center; width: 100px;">
                                <label>Mã đơn hàng</label>
                            </th>
                            <th style="text-align:center; width: 100px;">
                                <label>Mã sản phẩm</label>
                            </th>
                            <th style="text-align:center;">
                                <label>Tên sản phẩm</label>
                            </th>
                            <th style="text-align:center; width: 100px;">
                                <label>Giá</label>
                            </th>
                            <th style="text-align:center;">
                                <label>Ngày đặt hàng</label>
                            </th>
                            <th style="text-align:center;">Đánh giá</th>
                            <th style="text-align:center;"></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr style="padding:50px;">
                                <td>
                                    <a asp-controller="Product" asp-action="Details" asp-route-name="@item.Name.Replace(" ", "-").ToString()" asp-route-id="@item.ProductId">
                                        <img src="@item.ImgUrl" style="width:60px; height:90px; margin:auto; display:block; border-radius:5px; border:1px solid #bbb9b9" />
                                    </a>
                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(x => item.orderId)
                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(x => item.ProductId)
                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(x => item.Name)
                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(x => item.Price)
                                </td>
                                <td style="text-align:center;">
                                    @Html.DisplayFor(x => item.OrderDate.UtcDateTime)
                                </td>
                                <td style="text-align:center">
                                    <button type="submit" class="btn btn-primary" asp-action="index" asp-controller="Ratings" asp-route-name="@item.Name.Replace(" ", "-").ToString()" asp-route-productId="@item.ProductId" asp-route-orderId="@item.orderId">
                                        <i class="far fa-star" style="color: yellow;"></i>
                                    </button>
                                </td>
                                <td style="text-align:center">
                                    @if (!item.Status)
                                    {
                                        <button type="submit" class="btn btn-danger" asp-action="remove" asp-route-productId="@item.ProductId" asp-route-orderId="@item.orderId">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    }
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </form>
}
else
{
    <strong style="text-align: center !important;">Không có đơn hàng nào. <a asp-controller="Home" asp-action="Index">Click vào đây để tiếp tục mua sắm!</a></strong>
}