Web.CustomerSite/ViewComponents/TypeMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.CustomerSite.Services;

namespace Web.CustomerSite.ViewComponents
{
    public class TypeMenuViewComponent : ViewComponent
    {
        private readonly ICategoryApiClient _categoryApiClient;

        public TypeMenuViewComponent(ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var types = await _categoryApiClient.GetCategory();
            return View(types);
        }
    }
}

Web.CustomerSite/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Web.CustomerSite.Extentions

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.CustomerSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/RateStyleSheet.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/fc1632017d.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Web.CustomerSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @await Component.InvokeAsync("TypeMenu")
                @if (HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart") != null)
                {
                    <a asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                        <i class="fas fa-shopping-cart"></i> &nbsp;
                        @{
                            var count = HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart").Count;
                        }
                        (@count)
                    </a>
                }
                else
                {
                    <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                        <i class="fas fa-shopping-cart"></i> &nbsp;

                        (0)
                    </a>
                }
                @if (User.Identity.IsAuthenticated)
                {
                    <a asp-controller="Order" asp-action="Index" class="nav-link text-dark">My Order</a>
                }
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Web.CustomerSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web.CustomerSite/Views/Shared/_PaginatePartial.cshtml
@model Web.CustomerSite.Models.PaginateRouteVm

<div style="display: flex; justify-content: center;">
    <div class="Col">
        <ul class="pagination">
            @if (Model.previousPage == "Yes")
            {
                <li class="page-item">
                    <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage - 1)" class="page-link">
                        <i class="fas fa-backward"></i>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage - 1)" class="page-link">
                        <i class="fas fa-backward"></i>
                    </a>
                </li>
            }

            @if (Model.totalPages > 2)
            {
                @if (Model.currentPage != Model.totalPages && Model.currentPage != 1)
                {
                    <li class="page-item">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage - 1)" class="page-link">
                            @Model.GetPreviousPage()
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage)" class="page-link">
                            @Model.currentPage.ToString()
                        </a>
                    </li>
                    <li class="page-item">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage + 1)" class="page-link">
                            @Model.GetNextPage()
                        </a>
                    </li>
                }

                @if (Model.currentPage == 1)
                {
                    <li class="page-item disabled">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage)" class="page-link">
                            1
                        </a>
                    </li>
                    <li class="page-item">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage + 1)" class="page-link">
                            2
                        </a>
                    </li>
                    <li class="page-item">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage + 2)" class="page-link">
                            3
                        </a>
                    </li>
                }

                @if (Model.currentPage == Model.totalPages)
                {
                    <li class="page-item btn-primary">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage - 2)" class="page-link">
                            @Model.GetSecondPreviousPage()
                        </a>
                    </li>
                    <li class="page-item">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage - 1)" class="page-link">
                            @Model.GetFisrtPreviousPage()
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage )" class="page-link">
                            @Model.totalPages
                        </a>
                    </li>
                }
            }

            @if (Model.nextPage == "Yes")
            {
                <li class="page-item">
                    <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage + 1)" class="page-link">
                        <i class="fas fa-forward"></i>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item disabled">
                    <a asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-pageNumber="@(Model.currentPage + 1)" class="page-link">
                        <i class="fas fa-forward"></i>
                    </a>
                </li>
            }
        </ul>
        <small style="display: flex; justify-content: center;">@Model.GetCurrentPerTotalPage()</small>
    </div>
</div>